server:
  port: 8888
eureka: 
  server:
    enable-self-preservation: false # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 1000       # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
  instance:
    hostname: eurekaserver
  client: 
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://localhost:8888